apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: pipingdb-frontend
  name: pipingdb-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      run: pipingdb-frontend
  template:
    metadata:
      labels:
        run: pipingdb-frontend
    spec:
      containers:
      - image: gcr.io/kuber-test-263901/pipingdb-frontend:latest
        name: pipingdb-frontend
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
