apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "hello-static"
    kubernetes.io/ingress.allow-http: "false"
    ingress.kubernetes.io/force-ssl-redirect: "true" 
spec:
  tls:  
  - secretName: sslcerts
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: hello-service
          servicePort: 80
      - path: /veb
        backend:
          serviceName: pipingdb-backend-service
          servicePort: 
      - path: /vef
        backend:
          serviceName: pipingdb-frontend
          servicePort: 80
